### ISSUE TITLE
Keep track of scores

### ISSUE THREAD

**Issue by SaschaMann** [SaschaMann/TriviaBot#5]
Store user scores in a redis store.

Ask @RonakR for more info.

**Comment by HackToHell** [comment]
@RonakR Could you provide more details, I looks through the code and this seems to be the best place to push to redis. https://github.com/SaschaMann/TriviaBot/blob/develop/triviabot/mod_trivia.py#L16.

I'll push userame,score as key,value to redis. Will need to add a command to wipe the scores too as usernames keep changing in IRC. Is this okay, or do you have something else in mind.

**Comment by RonakR** [comment]
@HackToHell That sounds good. 

But, instead of wiping them we'll have a command to merge usernames. That way if someone keeps changing usernames they can still bring their score with them. As for the inactive ones, they eventually get drowned out by the active ones.

You do not need to worry about the merging in this PR. We'll leave that for a later one.

**Comment by HackToHell** [comment]
Okay, let me first add a MR to enable push to redis, will start work on the commands next. I will do the work from the develop branch.
